In [4]:
import pandas as pd
import numpy as np

# 1. Load dataset - simple variable

In [11]:
df = pd.read_csv("./test.csv")
df.head()

x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [12]:
X = df['x'].values.reshape(-1,1)
y = df["y"].values

## 1-1. Build Model

In [31]:
import normal_equation_lr as linear_model
import imp
imp.reload(linear_model)

<module 'normal_equation_lr' from 'C:\\Users\\user\\ML_study\\normal_equation_lr.py'>

In [37]:
lr = linear_model.LinearRegression()

In [38]:
lr.fit(X,y)

In [39]:
lr.intercept

-0.46181077366111367

In [40]:
lr.coef

array([1.01433536])

In [41]:
lr.predict(X)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

## 1-2. Validation

In [42]:
from sklearn import linear_model
sk_lr = linear_model.LinearRegression(normalize=False)
sk_lr.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [43]:
sk_lr.intercept_

-0.4618107736611847

In [45]:
import numpy.testing as npt
npt.assert_almost_equal(sk_lr.intercept_, lr.intercept)

In [46]:
sk_lr.coef_

array([1.01433536])

In [47]:
np.isclose(lr.coef, sk_lr.coef_)

array([ True])

In [48]:
lr.predict(X)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

In [49]:
df_test = pd.read_csv("train.csv")
df_test.head()

x          y
0  24  21.549452
1  50  47.464463
2  15  17.218656
3  38  36.586398
4  87  87.288984

In [51]:
X_test = df["x"].values.reshape(-1,1)

In [52]:
lr.predict(X_test[:5])

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201])

In [53]:
sk_lr.predict(X_test)[:5]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201])

# 2.Load dataset - multiple variables

In [54]:
df = pd.read_csv("mlr09.csv")
df.head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  average_points_scored  
0                              0.672                    9.2  
1                              0.797                   11.7  
2                              0.761                   15.8  
3                              0.651                    8.6  
4                              0.900                   23.2

In [55]:
y = df['average_points_scored'].values

In [57]:
df.iloc[:,:-1].head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  
0                              0.672  
1                              0.797  
2                              0.761  
3                              0.651  
4                              0.900

In [58]:
#y에 해당하는 마지막 열 제외하고 X에 저장
X = df.iloc[:,:-1].values

## 2-1. Rescaled

In [59]:
mu_X = np.mean(X, axis=0)
std_X = np.mean(X, axis=0)

rescaled_X = (X-mu_X) / std_X

In [60]:
rescaled_X[:5]

array([[ 0.03233062,  0.07190119, -0.01583375, -0.09415876],
       [-0.04357605, -0.14247905, -0.03142009,  0.07433849],
       [-0.02839471, -0.09483899,  0.01533894,  0.02581128],
       [-0.05875738, -0.14247905, -0.07372588, -0.1224663 ],
       [ 0.04751195, -0.02337891, -0.0002474 ,  0.21318023]])

## 2-2. Validation

In [61]:
lr.fit(rescaled_X,y)

In [62]:
lr.coef

array([-24.30945415,   1.98540037,  21.53047611,   8.4356117 ])

In [63]:
lr.intercept

11.790740740740738

In [64]:
sk_lr.coef_

array([1.01433536])

In [65]:
sk_lr.intercept_

-0.4618107736611847